name: ww4ff
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - ffmpeg=3.1.3
  - freetype=2.9.1
  - gettext=0.19.8.1
  - intel-openmp=2020.0
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libogg=1.3.2
  - libpng=1.6.37
  - libsndfile=1.0.28
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libvorbis=1.3.6
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.0.0
  - pip=20.0.2
  - python=3.7.7
  - python_abi=3.7
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tqdm=4.45.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - audioread==2.1.8
    - cffi==1.14.0
    - coloredlogs==14.0
    - decorator==4.4.2
    - humanfriendly==8.2
    - joblib==0.14.1
    - librosa==0.7.2
    - llvmlite==0.32.0
    - numba==0.49.0
    - pandas==1.0.3
    - pycparser==2.20
    - pydantic==1.5.1
    - python-dateutil==2.8.1
    - pytz==2020.1
    - resampy==0.2.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - soundfile==0.10.3.post1
